export const BOTAO_CLICADO_SUCESS = 'BOTAO_CLICADO_SUCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_RFAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_RFAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';